version: 0.2

env:
  variables:
    S3_BUCKET: "gyve.to"
phases:
  build:
    commands:
      - aws s3 sync . s3://${S3_BUCKET} --acl public-read --region eu-west-2 --delete
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E32V65DYN5IOK4 --paths "/*"

