version: 0.2

env:
  variables:
    S3_BUCKET: "gyve.to"
phases:
  build:
    commands:
      - aws s3 sync . s3://${S3_BUCKET} --acl public --region ${AWS_REGION} --delete
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E2J8YFX69AMRUN --paths "/*"

