version: 2
jobs:
  build:
    branches:
      only: gh-pages
    working_directory: ~/project/
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Deploy to S3
          command: aws s3 sync . s3://gyve.to/ --delete --acl public-read
