version: 2
jobs:
  # build job omitted for brevity
  deploy:
    branches:
      only: gh-pages
    working_directory: ~/project
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: List folders
          command: ls
      - run:
          name: Deploy to S3
          command: aws s3 sync . s3://gyve.to/ --delete --acl public-read
