version: 2
jobs:
  # build job omitted for brevity
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: List folders
          command: ls -a
      - run:
          name: Deploy to S3
          command: aws s3 sync . s3://gyve.to/ --delete --acl public-read

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: gh-pages
